### ISSUE TITLE
Yahoo weather source unavailable

### ISSUE THREAD

**Issue by peterLaurence** [atareao/my-weather-indicator#1]
It has been around 3 days that the Yahoo source is unavailable to me (see the image below where i erase the city name). 

![image](https://cloud.githubusercontent.com/assets/15638794/14078829/32d18d66-f4f9-11e5-8e5c-7c7e8e2ea27f.png)

**Comment by atareao** [comment]
Yahoo changed its API in order to increase the security. I updated MWI and addapted to this new API. New version of MWI was released, please update and upgrade, and tell me if it works correctly for you

Thanks

**Comment by peterLaurence** [comment]
I can confirm it works back on. Thanks!

BTW, your app is the best weather widget app for linux, good job!
