### ISSUE TITLE
resolved - Weather Data Missing: Openweather Invalid API Key & wyahooapi.py: error

### ISSUE THREAD

**Issue by tuxaddict** [atareao/my-weather-indicator#106]
### resolved

Hello Atareao,
first let me thank  you for this fantastic software. Should be a standard in e.g. Ubuntu Unity.

Since a few days, there is no more weather data fetched, the app itself seem to work perfect.
From the logs, i see that:

1. openweather has an connection error
`Error accessing url:  http://api.openweathermap.org/data/2.5/find?lat=51.8736674&lon=9.5031011&cnt=1&appid=4516154e5c8a6494e7e13b550408c863 401`
Trying to access that URL with a browser, gives:
`{"cod":401, "message": "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."}`

2. Unfortounatly, switching to yahoo as a source service is failing as well:
`wyahooapi.py: error: HTTPSConnectionPool(host='query.yahooapis.com', port=443): Max retries exceeded with url: /v1/yql?q=select%20*%20from%20weather.forecast%20where%20woeid=12833919&format=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f22df6c9c00>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))`

Any ideas on this? Thanks Everybody for your help, and have a great Weekend (-: 

ps: **Version**
> #####################################################
System: Linux
Machine: x86_64
Node: pro
Release: 5.19.0-38-generic
Version: #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 17:33:16 UTC 2023
Platform: Linux-5.19.0-38-generic-x86_64-with-glibc2.36
My-Weather-Indicator version: 0.9.5-0extras20.04.11
#####################################################

**Comment by tuxaddict** [comment]
Tried complete fresh install with purge, get the following error now:

> Namespace GeocodeGlib not available
Repository version required not present

**Comment by atareao** [comment]
Please, addi the repository:

sudo add-apt-repository ppa:atareao/atareao

and then updating:

sudo apt update 
sudo apt upgrade

**Comment by tuxaddict** [comment]
hello atareao,
thank you for your time! no, a fresh install, and i just tried again to try if something changed in the repo, doesn't help.
i still have the:
> Namespace GeocodeGlib not available for version 1.0
Repository version required not present

in the terminal and the app doesn't start, as indicated in [this comment](https://github.com/atareao/my-weather-indicator/issues/106#issuecomment-1509626855)

**Comment by tuxaddict** [comment]
### resolved

by simply fresh installing as [atarearo suggested here](https://github.com/atareao/my-weather-indicator/issues/106#issuecomment-1510084620). If you are on ubuntu 22.10 or 23.04. then this is your solution if the app doesn't start after a fresh install: [post](https://github.com/atareao/my-weather-indicator/issues/111#issuecomment-1513441270)

**Comment by atareao** [comment]
Fixed on  my-weather-indicator - 0.10.2-0extras23.04.00
