### ISSUE TITLE
No image for thunderstorm with light hail

### ISSUE THREAD

**Issue by gimplyworxs** [atareao/my-weather-indicator#112]
I still have a missing symbol on the widget:
I guess it could  be "thunderstorm with light hail"

This is the terminal output when starting the app:

[my-weather-indicator_na.txt](https://github.com/atareao/my-weather-indicator/files/11300707/my-weather-indicator_na.txt)

**Comment by atareao** [comment]
Thank you very much @gimplyworxs .... 
Upload a new version

**Comment by atareao** [comment]
Fixed with last update
