### ISSUE TITLE
No longer works in Ubuntu 16.04

### ISSUE THREAD

**Issue by floring67** [atareao/my-weather-indicator#116]
It seems that version 0.9.5 which still worked on Ubuntu 16.04 was no longer able to connect to any weather service. The system performed an automatic update to 0.10.5, but this version is not working at all, it crashes with the following error:

Traceback (most recent call last):
  File "./my-weather-indicator", line 35, in <module>
    from myweatherindicator import main
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 910
    logger.info(f"My-Weather-Indicator version: {comun.VERSION}")
                                                               ^
SyntaxError: invalid syntax

I did an install of gir1.2-ayatanaappindicator3-0.1 (needed for version 0.10.6) from package files (no problems with it and dependencies), I was able to install 0.10.6 but it crashes with the same error; might that be a Python 3 version compatibility (the latest version in Ubuntu 16.04 is 3.5.1)?

**Comment by floring67** [comment]
Checked the sources, it seems to come from the 'f' character before the string, Python 3.5.1 does not understand that

**Comment by urosg3** [comment]
Confirmed here as well. Same version and same Traceback

**Comment by atareao** [comment]
Thanks I will remove f-string to avoid this problem in old versions
Thanks for your feedback

**Comment by atareao** [comment]
Fixed in my-weather-indicator - 0.10.11-0extras23.04.00

**Comment by floring67** [comment]
Hi, I confirm the latest update works. I had to delete the old config file and the Python cache in the installation directory tho in order to make it work (this info might be useful for the other users who had this problem).
