### ISSUE TITLE
Latest version won't open

### ISSUE THREAD

**Issue by marsdenf** [atareao/my-weather-indicator#120]
Latest version (april 28 2023) won't open.  Here is error message from terminal:

              marsdenf@marsdenf-Desktop:~$ /opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator
Namespace AppIndicator3 not available
Repository version required not present
marsdenf@marsdenf-Desktop:~$

**Comment by marsdenf** [comment]
forgot to mention:  using xubuntu 22.04 on both a laptop and a desktop.  (same problem on both)

**Comment by bornagainpenguin** [comment]
I had this same issue, same error message on Ubuntu-Mate 22.04.2 LTS and the solution for me was to manually install in terminal:

`sudo apt install gir1.2-appindicator3-0.1`

Posting this in hopes of helping others.
