### ISSUE TITLE
New issue with the location map

### ISSUE THREAD

**Issue by venetin** [atareao/my-weather-indicator#121]
Hello,
When I search for a location the map is not shown. Instead the following error appeared: Error opening file /opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/whereami/whereami.html: No such file or directory
The error does not prevent the location search. Only the map is not shown.
Probably the issue is related to fact that some resources are removed in the last version:
diff -Nru my-weather-indicator-0.10.10/debian/changelog my-weather-indicator-0.10.11/debian/changelog
--- my-weather-indicator-0.10.10/debian/changelog	2020-12-05 18:37:44.000000000 +0000
+++ my-weather-indicator-0.10.11/debian/changelog	2020-12-05 18:37:44.000000000 +0000
@@ -1,4 +1,4 @@
-my-weather-indicator (0.10.10-0extras23.04.00) jammy; urgency=medium
+my-weather-indicator (0.10.11-0extras23.04.00) jammy; urgency=medium
 
   *  issue donВґt fix #119
 
diff -Nru my-weather-indicator-0.10.10/debian/install my-weather-indicator-0.10.11/debian/install
--- my-weather-indicator-0.10.10/debian/install	2020-12-05 18:37:44.000000000 +0000
+++ my-weather-indicator-0.10.11/debian/install	2020-12-05 18:37:44.000000000 +0000
@@ -1,8 +1,6 @@
 bin /opt/extras.ubuntu.com/my-weather-indicator
 debian/changelog /opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator
 src/*.py /opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator
-src/graph /opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator
-src/whereami /opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator
 data/logos /opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator
 data/social /opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator
 data/images /opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator

**Comment by atareao** [comment]
Fixed in version 0.10.12-0extras23.04.00
Thanks for your feedback @venetin
