### ISSUE TITLE
Unable to install on Ubuntu 24.04 LTS due to outdated dependecies

### ISSUE THREAD

**Issue by KanadaDEV** [atareao/my-weather-indicator#133]
Hello,

I can't install my-weather-indicator on Ubuntu 24.04 LTS due to outdated dependecies:
```

apt install my-weather-indicator 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 my-weather-indicator : Depends: gir1.2-webkit2-4.0 but it is not installable
E: Unable to correct problems, you have held broken packages.

```

The gir1.2 has been changed in the latest Ubuntu:
```
apt policy gir1.2-webkit2-4.1
gir1.2-webkit2-4.1:
  Installed: 2.44.2-0ubuntu0.24.04.2
  Candidate: 2.44.2-0ubuntu0.24.04.2
  Version table:
 *** 2.44.2-0ubuntu0.24.04.2 500
        500 http://pl.archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     2.44.2-0ubuntu0.24.04.1 500
        500 http://security.ubuntu.com/ubuntu noble-security/main amd64 Packages
     2.44.0-2 500
        500 http://pl.archive.ubuntu.com/ubuntu noble/main amd64 Packages
```

**Comment by marsdenf** [comment]
I have the same problem on Xubuntu 24.04

**Comment by rdh76** [comment]
Same.

**Comment by jagnthr** [comment]
same using linux mint 22
on linux mint 21.3 not an issue

**Comment by freewee** [comment]
Hi 
I have multiboot Ubuntu/Mint:
I think it' s strange, but when upgrading from Ubuntu 22.04 to 24.04, there is no problem, My Weather Indicator is still working...
But with Linux Mint, on 2 PCs, It' s impossible to upgrade from Mint 21 to 22, so after a fresh install of 22, I have the same problem as you of dependencies!

**Comment by alf-lmint** [comment]
> same using linux mint 22 on linux mint 21.3 not an issue

Same for me!

**Comment by atareao** [comment]
Today I uploaded new version, please check if it fixes the problem

**Comment by gimplyworxs** [comment]
There are still some references like this in there:
`gi.require_version('WebKit2', '4.0')`

which should probably be WebKit2', '4.1'

**Comment by marsdenf** [comment]
Using Xubuntu 24.04.  The program now installs successfully, but does not run when the menu entry is clicked.  In terminal, there is this error message:

Namespace WebKit2 not available for version 4.0
Repository version required not present

**Comment by Yen-Yung** [comment]
Same. I am on Ubuntu 24.04.
> Namespace WebKit2 not available for version 4.0
> Repository version required not present

**Comment by marsdenf** [comment]
Now working perfectly (Xubuntu 24.04)  Thank you to developers.

**Comment by freewee** [comment]
Thank you Atareao!
