### ISSUE TITLE
Error when weather is "blustery"

### ISSUE THREAD

**Issue by pekman** [atareao/my-weather-indicator#15]
When the error occurs, "Error: blustery" is shown as the last weather item in the menu, and an icon with question mark is shown as the weather icon.
Using Yahoo as weather service.

**Comment by csola48** [comment]
too => 
![kepmentes_016](https://cloud.githubusercontent.com/assets/893186/20491880/1fed99ee-b013-11e6-804a-f6d7a330ba55.png)
Error: blustery

**Comment by Bernmeister** [comment]
Same problem using the Open Weather Map service and version 0.8.1-0extras16.04.1 of the indicator.

**Comment by Spurlos** [comment]
When will this issue be fixed? Looks like the milestone is past due 10 months. Is this project abandoned?

**Comment by atareao** [comment]
HI, I'm working right now to fix it!

**Comment by 1dragosh** [comment]
Any news on the Bluestery Icon?

**Comment by atareao** [comment]
Fixed

**Comment by cement-head** [comment]
Will the PPA be updated?

**Comment by atareao** [comment]
Yes. The PPA is ypdated right now.
Please try it.

**Comment by cement-head** [comment]
Doesn't work.  New build does not connect to the Internet.

**Comment by cement-head** [comment]
Okay, does not connect to the Internet from my workplace (a University), but connects from home.  This means that the new build is trying to access the Internet differently.  A different port?  protocol?  What changed?

**Comment by atareao** [comment]
**Updated** again. Please, try it.

**Comment by cement-head** [comment]
How do I do that?  Is it in the PPA?On Thu, 2017-11-09 at 19:41 +0000, Lorenzo Carbonell wrote:

**Comment by cement-head** [comment]
Nevermind, it just came through. Working as expected.  Thanks!On Thu, 2017-11-09 at 19:41 +0000, Lorenzo Carbonell wrote:
