### ISSUE TITLE
Sydney Australia - Sunrise and SunSet times are wrong

### ISSUE THREAD

**Issue by kyleamadio** [atareao/my-weather-indicator#17]
Sydney Australia - Sunrise and SunSet times are wrong

![ame_17 18 22](https://cloud.githubusercontent.com/assets/1647986/16610291/c554c6c4-439d-11e6-8293-11f266b58a8e.png)

**Comment by Bernmeister** [comment]
Is this still an issue?  I am using Open Weather Map as the source (and I live in Sydney) and have not noticed any incorrect times.
