### ISSUE TITLE
Update Breaks Applet

### ISSUE THREAD

**Issue by cement-head** [atareao/my-weather-indicator#2]
Latest Update to the weather applet breaks the applet. April 3rd, 2016

See broken applet screenshot (square with red circle and line through it)

![screenshot from 2016-04-04 09-23-34](https://cloud.githubusercontent.com/assets/1056700/14249275/090aa06e-fa47-11e5-912d-f2d1b449a5e6.png)

**Comment by adatum** [comment]
I initially observed the same issue after the latest update (v0.7.6-0extras15.10.0), but then it "fixed" itself. I can see one of the "moon phase" icons similarly broken in the forecast.

![broken](https://cloud.githubusercontent.com/assets/9773655/14266358/aca08f6a-fa95-11e5-88e3-77f9a36cd289.png)

**Comment by cement-head** [comment]
Mine still broke.  What version of Ubuntu are you using?

**Comment by adatum** [comment]
Ubuntu 14.04 LTS.

**Comment by cement-head** [comment]
On 15.10, it's still broken.

**Comment by cement-head** [comment]
Okay, the new update (as of yesterday) doesn't get weather information at my workplace, whereas the last build did.  What changed in the retrieval method(s,) ports, etc?

**Comment by atareao** [comment]
Please kill my-weather-indicator and start it again. Please, tell me the result...
thanks.

**Comment by cement-head** [comment]
New build installed; still "No Internet"
Works from home, doesn't work from work-place.  Must be 
routing/listening differently.On Thu, 2017-11-09 at 16:33 +0000, Lorenzo Carbonell wrote:

**Comment by atareao** [comment]
But, do you kill my-weather-indicator? Please, run it from terminal, and paste here the output, so I can see what is the bug. For me is working ok.
To run MWI from terminal /opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator
Thanks...

**Comment by cement-head** [comment]
$ /opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator
<gettext.GNUTranslations object at 0x7f65e766a898>
#####################################################
System: Linux
Machine: x86_64
Node: *************
Release: 4.10.0-39-generic
Version: #43~16.04.1-Ubuntu SMP Fri Nov 3 08:19:53 UTC 2017
Platform: Linux-4.10.0-39-generic-x86_64-with-Ubuntu-16.04-xenial
My-Weather-Indicator version: 0.9.0-0extras17.10.2
#####################################################
****** Requesting timezone identificacion
** OWM **
redacted
1
***** refreshing weather *****
No internet connection available.
^^^^^ [Errno 111] Connection refused ^^^^^
No internet connection available.
--- Not internet connection ---
*** Looking For Internet ***
No internet connection available.
^^^^^ [Errno 111] Connection refused ^^^^^
No internet connection available.
*** Internet Not Found ***
*** Looking For Internet ***
No internet connection available.
^^^^^ [Errno 111] Connection refused ^^^^^
No internet connection available.
*** Internet Not Found ***On Thu, 2017-11-09 at 17:14 +0000, Lorenzo Carbonell wrote:

**Comment by atareao** [comment]
**Updated** again. Please, try it.
