### ISSUE TITLE
Preferences/Weather Service

### ISSUE THREAD

**Issue by rhowlett** [atareao/my-weather-indicator#20]
This is a really nice app and would like to see it get better.  So it wasn't exactly clear that the wUnderground.com entry was for the key.  I put my weather underground user name and then the app stopped working.  Thank goodness for easy to read .conf files, notices it was a key and everything is great once again.  Needless to say, the app shouldn't crash with the wrong info.  Maybe a simple check would be good before saving the info to the config file.

**Comment by invexx** [comment]
When I enter WU key, click Activate and press OK, the program won't run again. 
I have to delete .conf file to make it work again.

**Comment by mestremouro** [comment]
Are WUnderground and World Weather OnLine disabled??? How change weather services?

**Comment by atareao** [comment]
Removed old services
