### ISSUE TITLE
No "Blustery" Icon

### ISSUE THREAD

**Issue by cement-head** [atareao/my-weather-indicator#28]
Need a Blustery icon.

**Comment by Spurlos** [comment]
Duplicate of https://github.com/atareao/my-weather-indicator/issues/15 issue

**Comment by csola48** [comment]
There is no "Blustery" icon yet! ... :(

**Comment by 1dragosh** [comment]
This has been fixed [https://github.com/atareao/my-weather-indicator/issues/15#issuecomment-342414816]here.

**Comment by cement-head** [comment]
The new build won't connect to weather services (Yahoo, or OpenWeather) - it says "No internet connection"
