### ISSUE TITLE
Cannot change widget style after latest update (v0.7.6-0extras15.10.0)

### ISSUE THREAD

**Issue by adatum** [atareao/my-weather-indicator#3]
No matter which widget style is selected in Preferences, only one style (out of 9 available) appears. This happened only after updating to the latest version (v0.7.6-0extras15.10.0).

**Comment by adatum** [comment]
Also, the widget is showing on all workspaces even when that option is not selected in Preferences.

**Comment by adatum** [comment]
The update to version 0.7.7-0extras15.10.5 fixes both widget styles and workspace issues. Thanks!

**Comment by atareao** [comment]
Thank you.
