### ISSUE TITLE
Not displaying temperature in lxpanel

### ISSUE THREAD

**Issue by Nikola135** [atareao/my-weather-indicator#32]
I recently installed my-weather-indicator in Zorin OS 9 Lite (Lubuntu 14.04 based distribution). Since installation and setting city, my-weather-indicator only shows weather icon representing current weather, but not displaying current temperature. What can I do to fix this? Is this because of lxpanel or something else. It is getting weather information, and I can see current temperature when clicking on weather indicator in menu, but I would like to see it all the time, not having to click on it. 

I tried changing lxpanel width, icon size, panel orientation, font size; Also tried removing my-weather-indicator and reinstalling again, tried installing some older version, I think it was 0.6.somethin, that didn't work at all. Of course, I looked at settings, and I have "show temperature" checked. I did even look at ~/.config/my-weather-indicator/my-weather-indicator.conf, and I couldn't see anything strange.

Here are some screenshot so you can see what is happening.

![2017-08-21-105133_1024x600_scrot](https://user-images.githubusercontent.com/16721247/29669832-048adab2-88e5-11e7-9a56-d21d2b056466.png)
![2017-08-21-105203_1024x600_scrot](https://user-images.githubusercontent.com/16721247/29669907-45da7bd0-88e5-11e7-9d03-91dd9f77bc6d.png)

**Comment by atareao** [comment]
Duplicates of #97
