### ISSUE TITLE
unable to autostart

### ISSUE THREAD

**Issue by wenxuedisi** [atareao/my-weather-indicator#33]
I find that this app cannot start automatically on my ubuntu OS even if I go to preference->general options and check the autostart icon.Every time I want to know the weather I had to open this app manually,it's a little troublesome.I wish you can help solve this problem.Thanks.

**Comment by Bernmeister** [comment]
For autostart to work (at least on my Ubuntu 14.04) you should have the path/file present:

`~/.config/autostart/my-weather-indicator-autostart.desktop`

Perhaps an error is occurring whilst running the indicator (or when the autostart file is being copied to that location), so try running the indicator from the terminal and see if any warnings/errors appear.
