### ISSUE TITLE
 DNS Requests for Baidu.com when running My Weather indicator

### ISSUE THREAD

**Issue by aproposnix** [atareao/my-weather-indicator#34]
Recently I noticed that there are a lot of DNS requests with Baidu.com whenever I am running MWI. Is this expected behaviour, and if so, could I get some clarification as to why?

At first I thought it might be because of the weather provider (yahoo) but I am seeing the DNS requests even on the other weather services.

Ubuntu 16.04
My-Weather-Indicator: 0.8.1-0extras16.04.1

EDIT:  Here's an example of the DNS log - this can be replicated simply by starting the application or by clicking update in the menu.

> Oct  5 18:16:49 dnsmasq[31211]: query[AAAA] api.openweathermap.org from 10.0.0.88
Oct  5 18:16:49 dnsmasq[31211]: forwarded api.openweathermap.org to 208.67.222.222
Oct  5 18:16:49 dnsmasq[31211]: reply api.openweathermap.org is NODATA-IPv6
Oct  5 18:16:50 dnsmasq[31211]: query[A] www.baidu.com from 10.0.0.88
Oct  5 18:16:50 dnsmasq[31211]: /etc/pihole/gravity.list www.baidu.com is 10.0.0.89
Oct  5 18:16:50 dnsmasq[31211]: query[AAAA] www.baidu.com from 10.0.0.88
Oct  5 18:16:50 dnsmasq[31211]: /etc/pihole/gravity.list www.baidu.com is 2a00:1028:8d1c:a66a:48c9:e32c:9c3b:e0a7
Oct  5 18:16:50 dnsmasq[31211]: query[A] api.openweathermap.org from 10.0.0.88
Oct  5 18:16:50 dnsmasq[31211]: cached api.openweathermap.org is 95.85.63.65
Oct  5 18:16:50 dnsmasq[31211]: cached api.openweathermap.org is 146.185.181.89
Oct  5 18:16:50 dnsmasq[31211]: cached api.openweathermap.org is 178.62.207.82
Oct  5 18:16:50 dnsmasq[31211]: query[AAAA] api.openweathermap.org from 10.0.0.88
Oct  5 18:16:50 dnsmasq[31211]: cached api.openweathermap.org is NODATA-IPv6
Oct  5 18:16:50 dnsmasq[31211]: query[A] api.openweathermap.org from 10.0.0.88
Oct  5 18:16:50 dnsmasq[31211]: cached api.openweathermap.org is 178.62.207.82
Oct  5 18:16:50 dnsmasq[31211]: cached api.openweathermap.org is 95.85.63.65
Oct  5 18:16:50 dnsmasq[31211]: cached api.openweathermap.org is 146.185.181.89
Oct  5 18:16:50 dnsmasq[31211]: query[AAAA] api.openweathermap.org from 10.0.0.88
Oct  5 18:16:50 dnsmasq[31211]: cached api.openweathermap.org is NODATA-IPv6
Oct  5 18:16:50 dnsmasq[31211]: query[A] www.baidu.com from 10.0.0.88
Oct  5 18:16:50 dnsmasq[31211]: /etc/pihole/gravity.list www.baidu.com is 10.0.0.89
Oct  5 18:16:50 dnsmasq[31211]: query[AAAA] www.baidu.com from 10.0.0.88
Oct  5 18:16:50 dnsmasq[31211]: /etc/pihole/gravity.list www.baidu.com is 2a00:1028:8d1c:a66a:48c9:e32c:9c3b:e0a7
Oct  5 18:16:50 dnsmasq[31211]: query[A] www.baidu.com from 10.0.0.88
Oct  5 18:16:50 dnsmasq[31211]: /etc/pihole/gravity.list www.baidu.com is 10.0.0.89
Oct  5 18:16:50 dnsmasq[31211]: query[AAAA] www.baidu.com from 10.0.0.88
Oct  5 18:16:50 dnsmasq[31211]: /etc/pihole/gravity.list www.baidu.com is 2a00:1028:8d1c:a66a:48c9:e32c:9c3b:e0a7
Oct  5 18:16:50 dnsmasq[31211]: query[A] api.openweathermap.org from 10.0.0.88
Oct  5 18:16:50 dnsmasq[31211]: cached api.openweathermap.org is 146.185.181.89
Oct  5 18:16:50 dnsmasq[31211]: cached api.openweathermap.org is 178.62.207.82
Oct  5 18:16:50 dnsmasq[31211]: cached api.openweathermap.org is 95.85.63.65
Oct  5 18:16:50 dnsmasq[31211]: query[AAAA] api.openweathermap.org from 10.0.0.88
Oct  5 18:16:50 dnsmasq[31211]: cached api.openweathermap.org is NODATA-IPv6
Oct  5 18:16:50 dnsmasq[31211]: query[A] api.openweathermap.org from 10.0.0.88
Oct  5 18:16:50 dnsmasq[31211]: cached api.openweathermap.org is 95.85.63.65
Oct  5 18:16:50 dnsmasq[31211]: cached api.openweathermap.org is 146.185.181.89
Oct  5 18:16:50 dnsmasq[31211]: cached api.openweathermap.org is 178.62.207.82
Oct  5 18:16:50 dnsmasq[31211]: query[AAAA] api.openweathermap.org from 10.0.0.88
Oct  5 18:16:50 dnsmasq[31211]: cached api.openweathermap.org is NODATA-IPv6

**Comment by 1dragosh** [comment]
These requests are made just to check if internet is available or offline.

**Comment by aproposnix** [comment]
@1dragosh thanks for the info. You answered my question for me.
