### ISSUE TITLE
"Intensity rain"

### ISSUE THREAD

**Issue by pasniak** [atareao/my-weather-indicator#36]
I see "Intensity rain" in the GUI. There is no such thing :-)  It is either a translation problem (High intensity rain would be "Heavy rain" and low intensity rain would be "Light rain") or a word High/Low is cut off somewhere.

![screenshot from 2017-11-05 11-46-25](https://user-images.githubusercontent.com/19778666/32416931-5b3e53ca-c21f-11e7-9376-afed4cad9083.png)

On Ubuntu 17.10, my-weather-indicator 0.8.1-0extras16.04.1

**Comment by atareao** [comment]
Fixed.
