### ISSUE TITLE
NEBN wind forecast in GUI

### ISSUE THREAD

**Issue by pasniak** [atareao/my-weather-indicator#37]
![screenshot from 2017-11-05 11-46-25](https://user-images.githubusercontent.com/19778666/32416931-5b3e53ca-c21f-11e7-9376-afed4cad9083.png)

I am not sure if B is the right letter there...

Possibly you mean NNE?

**Comment by atareao** [comment]
No,
NEBN means northeast by north according https://en.wikipedia.org/wiki/Points_of_the_compass.
Maybe it must be NEbN
Thanks

**Comment by pasniak** [comment]
Ha! Never heard of nor I have seen 32-point rose on any commercial weather website!  You guys must be sailors :)

Imho it would be easier to read wind universally if we had either True wind (in degrees) - or just 16-point wind one hears in TV weather forecasts.  

Small caps also probably works...
