### ISSUE TITLE
Remove duplicated code

### ISSUE THREAD

**Issue by diegolagoglez** [atareao/my-weather-indicator#39]
For example, functions 'redondea' and 'cambia' duplicated in 'forecastw.py', 'myweatherindicator.py' and 'weatherservice.py'.

Those functions are "the same" function but even with different signatures.

**Comment by Jalakas** [comment]
Thank you for pointing this out.

Started collecting and removing duplicate code here: 
https://github.com/atareao/my-weather-indicator/commit/399c18f06901180c59c63495d3f38d4eecc6646b

Do you have more duplicate code suggestions?

**Comment by diegolagoglez** [comment]
I've not found more duplicated code, but this change is a really good starting point.

Well done!
