### ISSUE TITLE
After software update False statement of "No Internet" in Ubuntu 16.04

### ISSUE THREAD

**Issue by RoyTheNewbie** [atareao/my-weather-indicator#40]
This morning, in Ubuntu 16.04, I updated the weather app, along with various other apps. It now does not function, FALSELY claiming there is no Internet connection.

**Comment by atareao** [comment]
I upload new version. Please try it.

**Comment by RoyTheNewbie** [comment]
Thanks but it still has the same problem.

**Comment by atareao** [comment]
Are you restart My-Weather-Indicator? Are you sure it's not working? maybe in background...
Please try to run it in terminal
/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator 

Thanks

**Comment by RoyTheNewbie** [comment]
I did restart My-weather-Incator. I am sure it is not working.
I ran it in the terminal, as you requested. This is what I got...

~$ /opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator
<gettext.GNUTranslations object at 0x7f798c87f828>
#####################################################
System: Linux
Machine: x86_64
Node: roy-ThinkPad-T60p
Release: 4.10.0-38-generic
Version: #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017
Platform: Linux-4.10.0-38-generic-x86_64-with-Ubuntu-16.04-xenial
My-Weather-Indicator version: 0.9.0-0extras17.10.2
#####################################################

****** Requesting timezone identificacion
** OWM **
5795013 -122.4276 48.4298
/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/skins/anotherone
/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/skins/anotherone
Your screen supports alpha channels!
1
***** refreshing weather *****
No internet connection available.
^^^^^ timed out ^^^^^
No internet connection available.
--- Not internet connection ---
*** Looking For Internet ***
No internet connection available.
^^^^^ timed out ^^^^^
No internet connection available.
*** Internet Not Found ***
*** Looking For Internet ***
No internet connection available.
^^^^^ timed out ^^^^^
No internet connection available.
*** Internet Not Found ***
*** Looking For Internet ***
No internet connection available.
^^^^^ timed out ^^^^^
No internet connection available.
*** Internet Not Found ***

**Comment by atareao** [comment]
**Updated** again. Please, try it.

**Comment by RoyTheNewbie** [comment]
I am a newbie so please remind me:
- How to update the app
- What commands I need exactly to run the app in the terminal.

Many thanks.

**Comment by Bernmeister** [comment]
Assuming you originally installed by adding the PPA (via a terminal):

`sudo add-apt-repository ppa:atareao/atareao`

then simply do an update:

`sudo apt-get update`

and run again (as mentioned earlier).

**Comment by RoyTheNewbie** [comment]
Thanks, sorry for forgetting how to do it.
I followed the instructions but still getting the same problem of falsely stating that there is no Internet connection. I wonder what could have caused this problem: I really liked the app.

**Comment by Bernmeister** [comment]
Ensure the indicator is not running (it only allows one instance at time as I understand).  From a terminal, check:

` ps -e | grep weather`

When you are positive no other processes are running, try running again (from the terminal).

**Comment by RoyTheNewbie** [comment]
Wow! success! Five minutes ago Software Updater notified me I had updates available for download. My Weather Indicator was one of the items. I used Software Updater to the do the download and installation. I then searched for the app in the HUD, found it, opened it up....and it worked!
Does that mean that my original installation many months ago was not bu using the PA method?
Anyway, thank you very much for fixing this for me :-). Please thank your colleague who also helped me.

**Comment by RoyTheNewbie** [comment]
I also just followed your request to run it again in the terminal, having made sure I had closed it first: it worked in the terminal as well!
It seems like everything now is COOL! Thanks again for fixing it!
