### ISSUE TITLE
After instalation first configuration shows  and than you cannot acces config nor close the app.

### ISSUE THREAD

**Issue by Netoperz** [atareao/my-weather-indicator#48]
I hace added ppa, installed using apt, started app, and i've seen configuration window. and i have closed it. now i cannot close app, and i do not know how to start configuration ones again

On left in menu i have icon , and choosing close app does nothing.

Topbar i have on left and i can't see any icon of this app.

Clicking on widget does nothing.

Uninstalling and purging and reinstalling does nothing, it remembers configuration even after purging cache, and starts without first configuration.

To close it i need to reboot the system.

Linux n37--Stellar 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu budgee

**Comment by Carottinger** [comment]
I just did a clean (and easy) upgrade to Juno and observe the same problem.

You don't have to reboot - just look for "the process" (it's a bit hidden as its a python thingy):
`ps -ef | grep my-weather`
should yield something like:
```
stefan    **8466**     1 11 19:48 ?        00:00:01 python3 /opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator
stefan    8503  8407  0 19:48 pts/0    00:00:00 grep my-weather
```
then just do a (replace 8466 with your process id):
`kill -9 <pid>`

This does not solve the problem but makes continuous work easier.

**Comment by atareao** [comment]
Fix on last update
