### ISSUE TITLE
Autolocation API geoip.nekudo.com has been shutdown

### ISSUE THREAD

**Issue by rwyarbrough** [atareao/my-weather-indicator#51]
Autolocation no longer works as the API for geoip.nekudo.com has been shutdown. This causes my-weather-initiator to crash and shut down with the following:

`/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator
<gettext.GNUTranslations object at 0x7feab4139978>
#####################################################
System: Linux
Machine: x86_64
Node: ZBook-vbox-ubuntu-mate-18
Release: 4.15.0-36-generic
Version: #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018
Platform: Linux-4.15.0-36-generic-x86_64-with-Ubuntu-18.04-bionic
My-Weather-Indicator version: 0.9.0-0extras17.10.4
#####################################################

****** Requesting timezone identificacion
** OWM **
4710826 -96.6247 32.7673
1
***** refreshing weather *****
OK. Internet connection. HTTPConnection: www.google.com
--- Updating data in location 0 ---
http://geoip.nekudo.com/api/
HTTPSConnectionPool(host='geoip.nekudo.com', port=443): Max retries exceeded with url: /shutdown (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))
Traceback (most recent call last):
  File "/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator", line 62, in <module>
    mwi = MWI()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 141, in __init__
    self.load_preferences()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 366, in load_preferences
    self.update_weather()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 156, in update_weather
    self.update_menu(i)
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 638, in update_menu
    lat, lon = ipaddress.get_current_location()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/ipaddress.py", line 114, in get_current_location
    ans = json.loads(comun.read_from_url(url))
  File "/usr/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'
`

If you try to access the location [http://geoip.nekudo.com/api/](http://geoip.nekudo.com/api/) manually in a browser the following is returned:

[https://geoip.nekudo.com/shutdown]
[Error Page when     "autolocation": true](https://geoip.nekudo.com/shutdown)

{

  "0": "##################################################################",
  "1": "#                                                                                                                               #",
  "2": "# IMPORTANT - PLEASE UPDATE YOUR API ENDPOINT                                   #",
  "3": "#                                                                                                                               #",
  "4": "# This API endpoint is deprecated and has now been shut down. To keep using   #",
         "# the Free Geolocation API, please update                                                             #",
  "5": "# your integration to use the new ipapi API endpoint, designed as a simple           #",
         "# drop-in replacement.                                                                                             #",
  "6": "# You will be required to create an account at https://ipapi.com and obtain an       #",
         "# API access key.                                                                                                    #",
  "7": "#                                                                                                                               #",
  "8": "# For more information on how to upgrade please visit our Github page at:           #",  
        "#  https://github.com/nekudocom/shiny_geoip#readme                                           #",
  "9": "#                                                                                                                               #",
  "a": "#################################################################"
 }

**Comment by Spurlos** [comment]
Looks like the app was update to use new api endpoint, but it still fails to retrieve that data, crashing the whole app on launch. Here is the log from console:
```
<gettext.GNUTranslations object at 0x7fa653d00ba8>
#####################################################
System: Linux
Machine: x86_64
Node: spurlos-ThinkPad-E580
Release: 4.15.0-36-generic
Version: #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018
Platform: Linux-4.15.0-36-generic-x86_64-with-Ubuntu-18.04-bionic
My-Weather-Indicator version: 0.9.1-0extras18.04.0
#####################################################

****** Requesting timezone identificacion
** OWM **
701404 35.3676448 46.8487478
1
***** refreshing weather *****
OK. Internet connection. HTTPConnection: www.google.com
--- Updating data in location 0 ---
https://api.ipgeolocation.io/ipgeo-bulk?apiKey=046d333eb187475e863d3778c8f6c93e
HTTPSConnectionPool(host='api.ipgeolocation.io', port=443): Max retries exceeded with url: /ipgeo-bulk?apiKey=046d333eb187475e863d3778c8f6c93e (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))
Traceback (most recent call last):
  File "./my-weather-indicator", line 60, in <module>
    mwi = MWI()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 123, in __init__
    self.load_preferences()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 348, in load_preferences
    self.update_weather()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 138, in update_weather
    self.update_menu(i)
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 620, in update_menu
    lat, lon = ipaddress.get_current_location()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/ipaddress.py", line 113, in get_current_location
    ans = json.loads(comun.read_from_url(url))
  File "/usr/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'
```

**Comment by atareao** [comment]
Fixed
