### ISSUE TITLE
async.py conflicts with dist-package pyexpect

### ISSUE THREAD

**Issue by palevell** [atareao/my-weather-indicator#52]
**Issue:**
my-weather-indicator quit working after being updated by `apt-get` on Ubuntu 18.04.  The syslog reports a syntax error (see below).

**Error:**
```python
File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 47, in <module>
 import preferences
File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/preferences.py", line 27, in <module>
 from whereami import WhereAmI
File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/whereami.py", line 33
 from async import async_function
          ^
 SyntaxError: invalid syntax
```

**Files:**
- `/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/async.py`
- `/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/whereami.py`
- `/usr/lib/python3/dist-packages/pexpect/async.py`

**Workaround:**
rename my-weather-indicator's `async.py` to `async_.py` and edit `whereami.py` as follows:
```python
# 2018-Oct-17 PAL - Renamed async.py to async_.py, due to a conflict with
#                   /usr/lib/python3/dist-packages/pexpect/async.py (Python 3.6+)
# from async import async_function
from async_ import async_function
```

**Comment by Spurlos** [comment]
Got this issue while upgrading to 19.10 today.
@atareao any chance to patch it and do a bugfix release?

**Comment by atareao** [comment]
I will work on this next week to fix it.
Thanks
