### ISSUE TITLE
Multiple Icons In The System Tray

### ISSUE THREAD

**Issue by 2635599** [atareao/my-weather-indicator#56]
i love the app, it's perfect for my needs. however i do have one issue. there are two systray icons, one you can see and one you can't.  if you have a fix or a suggestion how to fix it i'd be greatful. thanks

running kde neon latest version

https://vimeo.com/338119086

**Comment by 2635599** [comment]
might want to inform github they have a issue with post being duplicated.

**Comment by atareao** [comment]
How much locations do you have configurated?

**Comment by pakair** [comment]
The main location is checked, Portland but cannot tell if the second location is checked as well. If I check both primary and second, I get data for both cities.
