### ISSUE TITLE
Cannot Install My Weather Indicator

### ISSUE THREAD

**Issue by 2635599** [atareao/my-weather-indicator#58]
having an issue getting my weather indicator to install on kubuntu 19.04 disco dingo. i keep getting the following. any help and or suggestions would be greatly appreciated. thanks

```
sudo apt-get install my-weather-indicator
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
my-weather-indicator : Depends: gir1.2-webkit-3.0 but it is not installable
E: Unable to correct problems, you have held broken packages.
```
http://ubuntuhandbook.org/index.php/2016/04/weather-indicator-desktop-widget-ubuntu-16-04/

https://www.kubuntuforums.net/showthread.php/75567-Cannot-Install-My-Weather-Indicator?p=428204#post428204

Kubuntu 19.04 Kernel 5.1.7 - KDE Neon Kernel 5.1.7, 
nVidia 430 Driver, Asus 970 Gaming/Aura, AMD FX 6300, 16Gig DDR3, 
Samsung 120Gig 850 EVO, AOC 29" Ultra Wide 2560x1080, nVidia 750Ti,
USB 3 Card, Drives 2TB, 1.5TB, 1TB / 750Gig, 500Gig

**Comment by 2635599** [comment]
https://www.linuxquestions.org/questions/showthread.php?p=6006717#post6006717

**Comment by 2635599** [comment]
still nothing on this?

**Comment by 2635599** [comment]
that's cool just wanted some kind of update., thanks

**Comment by atareao** [comment]
@2635599 Fixed. I uploaded a new version right now. Please test it!!!

**Comment by 2635599** [comment]
cool i shall.

**Comment by 2635599** [comment]
ok i just installed and i get a popup notification and nothing else. no systray icon, no desktop widget even though i went into setting and made appropriate adjustments.  i use your ppa.

**Comment by atareao** [comment]
Please @2635599  run it in terminal so I can see the bug
Thanks

**Comment by 2635599** [comment]
run what in terminal? you mean reinstall mwi?

**Comment by atareao** [comment]
Run mwi
/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator

**Comment by 2635599** [comment]
the only items i have in /opt/extras.ubuntu.com/my-weather-indicator/ are a bin folder, a share folder, and my_weather_indicator-0.9.2.egg-info

**Comment by atareao** [comment]
Yes I said inside bin folder is the executable. Please run it
Thanks

**Comment by atareao** [comment]
@2635599 did you test mwi? Thanks

**Comment by 2635599** [comment]
yes i ran it as i stated above.  just ran it again and got the exact same thing. a notification pops up with the current conditions, then closes, but no tray icon or desktop widget.

**Comment by 2635599** [comment]
i figured you would of gotten back to me by now. i'm still having the same issue of rebooting the system and once on the desktop i get the mwi notification, and no systray icon, nor can i launch mwi from the start menu. thanks

**Comment by atareao** [comment]
Fix on last update
