### ISSUE TITLE
Forecast Map: overlays are not displayed 

### ISSUE THREAD

**Issue by msalini** [atareao/my-weather-indicator#60]
Hi,

I am on a LInux Mint 18.3 Sylvia (based on Ubuntu 16.04). I am using OpenStreetMap and OpenWeatherMap service (though it is the same with Yahoo!)
When I pull up the weather forecast map and try to display any of the overlays, they come up as broken image links. (see [image](http://imgur.com/2NuZhU8l.png) )

Any idea why?

**Comment by atareao** [comment]
Removed OpenWeahterMap
