### ISSUE TITLE
wrong Temperature unity in evolution screen.

### ISSUE THREAD

**Issue by mestremouro** [atareao/my-weather-indicator#61]
Using Celsius in configuration, but temperature shows as Fahrenheit in evolution screen.

![Captura de tela em 2019-11-06 21-34-27](https://user-images.githubusercontent.com/10165383/68350009-d0dae400-00dd-11ea-9974-71fa13451933.png)
![Seleção_160](https://user-images.githubusercontent.com/10165383/68350035-e2bc8700-00dd-11ea-870c-36a944e1adc0.png)

**Comment by atareao** [comment]
Please, what release do you have installed?
Recently I uploaded a fix for that
Thank you very much

**Comment by mestremouro** [comment]
![Seleção_162](https://user-images.githubusercontent.com/10165383/68509100-ee7b8b00-024e-11ea-811c-9a4448bbc23f.png)
Updated new version. Is all right now !
Thanks for your work !!!!
