### ISSUE TITLE
Preference and top section (Forecast, Evolution, etc.) greyed out after exiting Preference menu

### ISSUE THREAD

**Issue by busterwan** [atareao/my-weather-indicator#62]
The issue is indicated on the title of this message. The only things that work are Waxing Gibbous and Help. This is repeatable every time by entering Preference and then click exit.

System:
Host: Aspire5570 Kernel: 4.15.0-66-generic x86_64 bits: 64 compiler: gcc v: 7.4.
Desktop: Cinnamon 4.2.4 wm: muffin dm: LightDM Distro: Linux Mint 19.2 Tina
base: Ubuntu 18.04 bionic

Let me know if there are anything else that you need.

**Comment by atareao** [comment]
Hi, it is not a issue, it works to avoid to select other options while you change the configuration
