### ISSUE TITLE
Area locator does not work

### ISSUE THREAD

**Issue by Langjan** [atareao/my-weather-indicator#63]
My "My Weather Indicator" became unresponsive so I uninstalled and reinstalled it on Ubuntu 16.04 Unity 64-bit. It is running now, but has auto-located me incorrectly and I am unable to get any response from the "Search location" facility.

**Comment by Langjan** [comment]
After posting, I tried to select a second location which was successful. Then I tried the first location again and it worked. Seems as if the finding of the second location triggered something to work.

**Comment by poetician** [comment]
Installed on ArcoLinux running i3wm. Intermittent functionality. Neither first nor second location can be selected through the app. I have to edit the config manually. When I launch the app, the reports are completely out to lunch. For a while I could at least select the second location, but now not even that.

**Comment by atareao** [comment]
Fix on last update

**Comment by Langjan** [comment]
Great! Many thanks for the follow-up.

Installed and it's working.
