### ISSUE TITLE
Auto start function

### ISSUE THREAD

**Issue by ricelli-sudo** [atareao/my-weather-indicator#65]
I installed my-weather on Linux Mint 19.3 with Cinnamon interface, but in preferences I select the option to start automatically, but it does not work, and if I check the preferences again, the option is disabled, unless I close the application and bra again.
I want the widget to appear as soon as my system starts.
Thank you, overall my-weather is the best weather forecasting application I've ever used on linux.

**Comment by GraveDigger1** [comment]
i gave up on my-weather-indicator months ago. since one cinnamon update the app won't load properly. you'll get an occasions popup giving you weather info,no desktop widget, d no systray icon. found the same to be true in the latest kubuntu and neon releases. i've since switched to manjaro attempted to install via manjaro's software manand it's the same  as in ubuntu based systems.

**Comment by atareao** [comment]
Hi @ricelli-sudo I will review the installation in Linux Mint in a few days.
Thanks

**Comment by SanDroid77** [comment]
I have the same behavior on Ubuntu 19:10. It says that can't find file '/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/my-weather-indicator-autostart.desktop'.

**Comment by GraveDigger1** [comment]
f it helps manjaro kde  18.1.5 rc1 testing build.

**Comment by beew** [comment]
Similar issue on Ubuntu 20.04 (with unity desktop) my-weather-indicator can be started manually, but crashes right the way If check autostart in preference. However autostart works if entering the command into startup application instead of using my-weather-indicator's checkbox.

**Comment by SanDroid77** [comment]
@atareao I think that the my-weather-indicator-autostart.desktop file is not being copied when installing. I just copied manually the desktop file from the source code to `/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/`, and it worked.

**Comment by orabno** [comment]
Olá! Você poderia me ensinar a instalar o Weather Indicator no Fedora? Desde já, obrigado!

**Comment by atareao** [comment]
Fixed.

**Comment by csola48** [comment]
Dear atareao ! :)
It still worked yesterday, it won't start this morning and it's set to start automatically. In fact, if I run it separately, it won't move. It is marked as installed in synaptic. I do not know what to do? Version 0.9.5-0extras20.04.09 is installed ... 

Please help!
