### ISSUE TITLE
The application installed but will not launch (Ubuntu 16.04)

### ISSUE THREAD

**Issue by RoyTheNewbie** [atareao/my-weather-indicator#68]
I am using Ubuntu 16.04 on an old Thinkpad.

I have been using the _my-weather-indicator_ app for years and really like it. The indicator has started to malfunction: it will not launch. I removed the app, using Ubuntu Software, and then re-installed it. But it still fails to launch.

I am not a techie so don't really know how to troubleshoot the problem. I did notice that I had a roughly simultaneous problem, whereby wi-fi, which I had set to be enabled automatically, did not. I had to enable wi-fi manually. At the onset of the wi-fi  problem the weather app was still working, and I had it set to start automatically after my login.

This morning I was delighted when my wi-fi issue disappeared ans was automatically enabled after login. But at the same tome the weather app problem appeared.

Are the two issues logically connected? What else could be giving the problem?

Thanks in advance for any help with this issue.

Update:
With no advice yet received I removed the app today and then reinstalled it. This time it will launch and has two issues. First, it will not accept a text entry for my primary location so I am compelled to leave it on Auto-location. Second, when I tried to search for a secondary location the app stalled.

**Comment by atareao** [comment]
Fixed in last version
