### ISSUE TITLE
not available - not internet connection

### ISSUE THREAD

**Issue by JediBrooker** [atareao/my-weather-indicator#7]
firstly the error should say "No internet connection".

my real problem is that there is an internet connection but i still get this error for both yahoo and open weather map. 

i believe my internet connection is just slow. can you make it so that the app tries harder to find a connection? it seems as if the app tried to find data and if it doesn't get a response within 0.1 seconds it gives up!

**Comment by mvc1095** [comment]
In general better handling of the situation when the program can't connect would be useful.

![screenshot from 2017-03-11 07-40-29](https://cloud.githubusercontent.com/assets/675131/23827462/fc1abedc-0681-11e7-999a-37b66733ac5c.png)

**Comment by atareao** [comment]
Removed Yahoo and OpenWeatherMap
