### ISSUE TITLE
Cannot select Wunderground

### ISSUE THREAD

**Issue by fireshaper** [atareao/my-weather-indicator#71]
I'm using Ubuntu 20.04.

I input my WU API key and click Activate but nothing happens. I cannot select the WU option after that.

**Comment by erichlf** [comment]
The work-around would be to edit `weather-service` in `~/.config/my-weather-indicator/my-weather-indicator.conf`. After you edit that it will then allow you to change the weather service via gui.

**Comment by atareao** [comment]
I remove old services
