### ISSUE TITLE
Color pattern on Weather forecast

### ISSUE THREAD

**Issue by juceliohv** [atareao/my-weather-indicator#73]
Hello,

When i use the dark theme on Ubuntu Mate, the contrast between background colors and foreground colors are wrong.

![Captura de tela em 2020-08-05 15-55-15](https://user-images.githubusercontent.com/8875793/89452474-17747200-d734-11ea-9172-42bda2f73329.png)

**Comment by erichlf** [comment]
Using dark mode on Ubuntu 20.04 results in the same issue.

**Comment by atareao** [comment]
I changed the color pattern
