### ISSUE TITLE
Is this Project Maintained

### ISSUE THREAD

**Issue by erichlf** [atareao/my-weather-indicator#74]
I haven't seen much activity in the repo for over 10 months. However, there are bug reports stacking up. Heck there are bugs that are years old. Is this repo actively being maintained?

I would consider taking it over, but with the state of the code it would take some time to get up to speed before I could really start doing anything.

**Comment by bouxboux** [comment]
What if the developer has succumbed to teh Covid meme and no one knows it? Is 'My-Weather-Indicator' just another victim of the Covid crisis meme?

Smartass political comments aside, I'd really like to get this app working again. I hope someone can fix it properly.

**Comment by atareao** [comment]
Hi @erichlf . You are welcome if you want to contribute to this project.

I'm going yo work in MWI this month actively
