### ISSUE TITLE
C temperature units on axis, but F displayed

### ISSUE THREAD

**Issue by jnigrine** [atareao/my-weather-indicator#76]
Hello - What a great application, thank you!

I am using English units, but in the "Forecast for next hours" display, the temperature axis is labeled C, not F.  The values are Fahrenheit, but the axis labels are wrong.

![forecast-for-next-hours](https://user-images.githubusercontent.com/27712916/92541192-4be7bc00-f213-11ea-8131-ae2126b9662e.png)

Thank you so much for the program!
Jon

**Comment by atareao** [comment]
Fixed in last update
