### ISSUE TITLE
Position of the Desktop

### ISSUE THREAD

**Issue by adiwerner** [atareao/my-weather-indicator#77]
After installing the app its position on the Desktop is at the upper left corner.
I am trying to reposition it to the right upper corner and it is impossible to move it anywhere on the Desktop.
I am running Linux Mint 20 64bit.

**Comment by atareao** [comment]
Do you grab and move the widget?

**Comment by adiwerner** [comment]
I am trying but I can`t, there is no way to move it at all.

**Comment by bouxboux** [comment]
>  there is no way to move it at all.

Hold down Alt - click - drag.

**Comment by adiwerner** [comment]
You are the BEST!!! Thank you!
