### ISSUE TITLE
Fahrenheit numbers are correct, but are labelled centigrade in Evolution

### ISSUE THREAD

**Issue by bmenyuk** [atareao/my-weather-indicator#78]
The numbers in the forecast evolution graph are correct for Fahrenheit, but are labelled as centigrade, which would mean that the temperature outside later this week (80°) is fairly close to boiling!
Xubuntu Linux: 0.8.1-0extras16.04.1

![image](https://user-images.githubusercontent.com/37024456/94036660-8cf2db00-fd92-11ea-8ffe-aef46b602649.png)

**Comment by atareao** [comment]
Fixed
