### ISSUE TITLE
LM 19.3 MATE 64bit - Warning! Don't update my-weather-indicat

### ISSUE THREAD

**Issue by Lucafatichenti** [atareao/my-weather-indicator#79]
LM 19.3 MATE 64bit - Warning! Don't update my-weather-indicator
Post by Centauri39 » Thu Sep 03, 2020 5:17 am

For all of you who are running my-weather-indicator 0.9.5-0extras20.04.05.
Don't install the latest update 0.9.5-0extras20.04.09.
You will not be able to drag'n'drop the widget anymore and it will disappear when you touched the taskbar button of a kodi instance(*) in the task bar.

(*) maybe this is true for other apps, too.

**Comment by atareao** [comment]
Please try this shortcut to move Hold down Alt - click - drag.

**Comment by Lucafatichenti** [comment]
yes i tried to do it that way but then the widget always disappears. the previous version instead worked very well at least for me who use Linux Mint Mate 19.3 Trica

⁣LiberoMail

Ottieni BlueMail per Android ​

Il giorno 12 Ott 2020, 10:04, alle ore 10:04, Lorenzo Carbonell <notifications@github.com> ha scritto:
