### ISSUE TITLE
application crashing when using OpenWeatherMap

### ISSUE THREAD

**Issue by val-kulkov** [atareao/my-weather-indicator#81]
My Weather Indicator suddenly started crashing. When started in console, it displays the following error message:
```
...
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/wopenweathermapapi.py", line 277, in get_weather
    if CONDITION.has_key(data['weather'][0]['id']):
AttributeError: 'dict' object has no attribute 'has_key'
```
Apparently, OpenWeatherMap added some new keys that My Weather Indicator is not aware of. A PR to fix this issue will follow shortly.

**Comment by jstlavila** [comment]
Hola Atareao, para mi tampoco funciona la aplicacion conectado a openWeatherMap. Desde Canada, Ubuntu 20.04 en frances. Epero que que puedas corregir este fallo porque tu aplicacion es excelente. Gracias.

**Comment by DonkZZ** [comment]
I have the same problem

**Comment by DonkZZ** [comment]
This morning, the bug is gone
:confused:

**Comment by erichlf** [comment]
It's not gone. Your weather changed and is in the previous list of weather.
