### ISSUE TITLE
Icon not available

### ISSUE THREAD

**Issue by aplab** [atareao/my-weather-indicator#84]
Ubuntu 20.10

Package installed via ppa

![2020-12-18_12-52](https://user-images.githubusercontent.com/4007240/102588927-0569fd80-4130-11eb-9764-1481ff683ec1.png)

![2020-12-18_12-52_2](https://user-images.githubusercontent.com/4007240/102588896-fa16d200-412f-11eb-8736-3b4acc88338e.png)

![2020-12-18_12-52_1](https://user-images.githubusercontent.com/4007240/102588914-013de000-4130-11eb-9ac0-6360479c28d4.png)

**Comment by atareao** [comment]
Fixed on  my-weather-indicator - 0.10.2-0extras23.04.00
