### ISSUE TITLE
Ubuntu 16.04 not working

### ISSUE THREAD

**Issue by urosg3** [atareao/my-weather-indicator#85]
Hi mate

`uros@uros-M17xR3:~$ /opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator
<gettext.GNUTranslations object at 0x7ff8e7028ac8>
#####################################################
System: Linux
Machine: x86_64
Node: uros-M17xR3
Release: 4.15.0-117-generic
Version: #118~16.04.1-Ubuntu SMP Sat Sep 5 23:35:06 UTC 2020
Platform: Linux-4.15.0-117-generic-x86_64-with-Ubuntu-16.04-xenial
My-Weather-Indicator version: 0.9.5-0extras20.04.09
#####################################################

My-Weather-Indicator version: 0.9.5-0extras20.04.09
#####################################################
****** Requesting timezone identificacion
** OWM **
791148 20.4721 44.8166
1
***** refreshing weather *****
OK. Internet connection. HTTPConnection: www.google.com
--- Updating data in location 0 ---
****** Updating weather
****** Calculating rawOffset
-------------------------------------------------------
OpenWeatherMap Weather Service url:http://api.openweathermap.org/data/2.5/weather?id=791148&appid=4516154e5c8a6494e7e13b550408c863
-------------------------------------------------------
Traceback (most recent call last):
  File "/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator", line 36, in <module>
    main()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 956, in main
    MWI()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 126, in __init__
    self.load_preferences()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 352, in load_preferences
    self.update_weather()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 141, in update_weather
    self.update_menu(i)
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 669, in update_menu
    weather = self.weatherservices[index].get_weather()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/wopenweathermapapi.py", line 263, in get_weather
    condition = CONDITION[data['weather'][0]['id']]
KeyError: 616
uros@uros-M17xR3:~$ sudo apt install my-weather-indicator
[sudo] password for uros: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
my-weather-indicator is already the newest version (0.9.5-0extras20.04.09).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
uros@uros-M17xR3:~$ sudo apt install --reinstall my-weather-indicator
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 1 not upgraded.
Need to get 3879 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://ppa.launchpad.net/atareao/atareao/ubuntu xenial/main amd64 my-weather-indicator all 0.9.5-0extras20.04.09 [3879 kB]
Fetched 3879 kB in 3s (1219 kB/s)               
(Reading database ... 433897 files and directories currently installed.)
Preparing to unpack .../my-weather-indicator_0.9.5-0extras20.04.09_all.deb ...
Unpacking my-weather-indicator (0.9.5-0extras20.04.09) over (0.9.5-0extras20.04.09) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.2) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20180209-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for fontconfig (2.11.94-0ubuntu1.1) ...
Setting up my-weather-indicator (0.9.5-0extras20.04.09) ...
Any ideas?`

**Comment by jochen-st** [comment]
The fix is already contained in 4bfc87d6d778f27078c2ed3f061d26ab5051eb12. 

You could download the file https://raw.githubusercontent.com/atareao/my-weather-indicator/master/src/wopenweathermapapi.py and store it in /opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/wopenweathermapapi.py" or edit the file manually to add
~~~
CONDITION[616] = 'rain and snow'
~~~
in the appropiate place.

**Comment by atareao** [comment]
Fixed in last updated
