### ISSUE TITLE
Location issue

### ISSUE THREAD

**Issue by nawazdj** [atareao/my-weather-indicator#9]
This app cannot detect city or location itself. Even can't set manually. Is that a but or I'm missing something?

**Comment by leandroandrade87** [comment]
The same here.

**Comment by erichlf** [comment]
I know this is super old, but this still seems to be an issue and I have a work-around that I discovered while looking over the code in hopes that I could fix this. Anyway, you can edit ~/.config/my-weather-indicator/my-weather-indicator.conf and manually enter your location in that file.

**Comment by erichlf** [comment]
After using my working around the search location function now works. I am guessing it didn't work before because the string passed to the map was probably empty and it needed to have a default value?

**Comment by atareao** [comment]
Added a new version for locaitons
