### ISSUE TITLE
Doesn't work on Ubuntu 21.10

### ISSUE THREAD

**Issue by vrainish** [atareao/my-weather-indicator#90]
I changed distribution from Impish to Groovy as (it was advised for 20.04 ) and was able to install and launch it on 21.10
However it doesn't work properly. 
Shows Identical times for main and secondary locations and other issues.
It's dysfunctional and developers should fix it or , at least to   put explicit info with list of Ubuntu releases where it works

**Comment by DooMFeaR** [comment]
For myself, on Ubuntu 21.10, it cannot be found for installation. I have added the PPA but it's not able to locate the package to install.

**Comment by jryals** [comment]
gir1.2-geocodeglib-1.0 is not installed in 22.10, gir1.2-geocodeglib-2.0 is the only version installed on 22.10, the rest of the gir1.2-* dependencies appear to be installed. Not sure how it would behave with update from anything 22.04 and before to 22.10, but if you have issues, this may be the culprit.

**Comment by atareao** [comment]
I removed this dependency

Thanks for your report
