### ISSUE TITLE
Change Weather Server

### ISSUE THREAD

**Issue by papusone** [atareao/my-weather-indicator#92]
Hello !
How can i change weather server, because i have only to choice, Yahoo or Open weather, but **Yahoo** doesn't work and **Open weather** was always wrong ! There is two other choice with **Activate Button**, but it's do anything !
I use also in windows "**_Rainmeter and Vcloud Weather 2_**", which use another server **Weather.com** and which give better result for weather !
Thanks !

**Comment by atareao** [comment]
I removed old services
