### ISSUE TITLE
Can not install on Ubuntu 22.04

### ISSUE THREAD

**Issue by garyartista** [atareao/my-weather-indicator#93]
After adding the repository, message is " Unable to locate package my-weather-indicator."  Best weather app for Ubuntu so I hope you will make it work in 22.04

**Comment by atareao** [comment]
Hi. I will review in a few days 👍

**Comment by atareao** [comment]
Hi. I will review in a few days 👍

**Comment by DooMFeaR** [comment]
Same issue with Ubuntu 21.10 !

**Comment by enigma9o7** [comment]
Same, PPA doesn't contain jammy version.

**Comment by atareao** [comment]
@DooMFeaR I can't update for 21.10. It's not supported anymore

**Comment by atareao** [comment]
@DooMFeaR I can't update for 21.10. It's not supported anymore

@enigma9o7 what repository did you add?

**Comment by enigma9o7** [comment]
Yours, atareao/atareao.
