### ISSUE TITLE
No Applet Appears 

### ISSUE THREAD

**Issue by jvaccaro** [atareao/my-weather-indicator#95]
Running a fresh install of Ubuntu 20.04LTS. Installed my-weather-indicator using:
   sudo add-apt-repository ppa:atareao/atareao
   sudo apt update
    sudo apt install my-weather-indicator

Configured for my location and using the Open Weather API. 

Help->About says version 0.9.5-0extras20.04.11

When I launch my-weather-indicator from either the command line or via the icon, the Notification of Current Conditions appears as does the Indicator in the status bar.; but no widget ever appears.

I captured the console output to a test file and have attached it
[my-weather-indicator.log](https://github.com/atareao/my-weather-indicator/files/8734888/my-weather-indicator.log)
.

**Comment by atareao** [comment]
Fix in last update
